### ISSUE TITLE
[question] how to I remove source code.zip from the release?

### ISSUE THREAD

**Issue by yangcheng** [underwindfall/create-release-with-debugapk#2]
Thanks very much for creating the plugin. very useful.

is there a way to set so that only apk is in release, not source_code.zip ?

Thanks!

**Comment by underwindfall** [comment]
@yangcheng I think it's kind of out of scope for this library.  😉 

However, I take a quick look for this solution. It can be configured by the repository's settings. You can find more information from this [official documentation](https://docs.github.com/en/github/administering-a-repository/managing-git-lfs-objects-in-archives-of-your-repository)

**Comment by yangcheng** [comment]
I see, thanks! can the tag name read from git tag instead of hard code in yml file?

**Comment by underwindfall** [comment]
sure you may need to look at [this repository](https://github.com/underwindfall/PowerPermission/blob/master/.github/workflows/release.yml#L39), I can get the version tag from github_ref
```yml
     - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: Create Release and Upload debug APK
        uses: underwindfall/create-release-with-debugapk@v1.2.4
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: Example.apk
          asset_content_type: application/zip
          draft: false
          prerelease: false
```
